/* https://leetcode.com/problems/find-the-difference/#/description
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

    Input:
    s = "abcd"
    t = "abcde"

    Output:
    e

    Explanation:
    'e' is the letter that was added.
*/

package leetcode

func findTheDifference(s string, t string) byte {
	ss, ts := make([]int, 26, 26), make([]int, 26, 26)
	for _, letter := range s {
		ss[letter-'a']++
	}

	var r byte
	for _, letter := range t {
		ts[letter-'a']++
		if ts[letter-'a'] > ss[letter-'a'] {
			r = byte(letter)
			break
		}
	}
	return r
}
